### ISSUE TITLE
Package uses unsafe source of random

### ISSUE THREAD

**Issue by empijei** [srikrsna/security-headers#5]
This package uses math/rand (which is predictable) instead of crypto/rand (which is impossible to predict) to generate csp nonces.

**Comment by srikrsna** [comment]
I agree that crypto/rand is safer for generating secure random values. But for something like CSP Nonce I don't think that level of unpredictability is necessary. The only reason this package uses math/rand is for the performance gains.

We can implement a crypto/rand based generator as a configurable option in backwards compatible ways and try and amortise its generation. Or you can try this [package](https://github.com/unrolled/secure) which uses crypto/rand.

**Comment by srikrsna** [comment]
I am closing this issue for now. If you want to discuss further please let me know.

**Comment by empijei** [comment]
Note: this issue makes this package not compliant with the [CSP spec](https://w3c.github.io/webappsec-csp/#security-nonces).
Quoting:
`The generated value SHOULD be at least 128 bits long (before encoding), and SHOULD be generated via a cryptographically secure random`.

This is currently using a 63-bits long random from a predictable source. 

If you are ok with this it is fine, but you might want to document your decision.

**Comment by srikrsna** [comment]
Thanks for bringing this to my concern. I was ignorant of the CSP Spec. I'll change the function to use cryptographic source and try to amortise the generation.
